### ISSUE TITLE
[feature] Laravel 11 Support

### ISSUE THREAD

**Issue by aldinokemal** [emreyarligan/enum-concern#8]
Hi, your library is very usefull
Could you please also support for laravel 11?

<img width="1671" alt="Screenshot 2024-03-24 at 08 49 02" src="https://github.com/emreyarligan/enum-concern/assets/14232125/2fd19176-3e30-4085-89e1-6475b4cfee5c">

**Comment by emreyarligan** [comment]
https://github.com/emreyarligan/enum-concern/pull/7
